---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - sde.sde.domain
  resources:
  - sdes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sde.sde.domain
  resources:
  - sdes/finalizers
  verbs:
  - update
- apiGroups:
  - sde.sde.domain
  resources:
  - sdes/status
  verbs:
  - get
  - patch
  - update
